- hosts: localhost 
  connection: local
  gather_facts: False
  vars:
    guest_name: newvm001
    vmware_template: template_el7
  tasks:
    - vsphere_guest:
        validate_certs: no
        vcenter_hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        guest: "{{ guest_name }}"
        from_template: yes
        template_src: "{{ vmware_template }}"
        vm_extra_config:
          folder: testvms
        esxi:
          datacenter: datacenter1
          hostname: 172.16.141.128

    - vsphere_guest:
        validate_certs: no
        vcenter_hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        guest: "{{ guest_name }}"
        vmware_guest_facts: yes
      register: instance
      until: instance.ansible_facts.hw_eth0['ipaddress']
      retries: 10
      delay: 10

    - debug: var=instance        

