- hosts: all
  user: root
  gather_facts: False
  tasks:

    - debug: msg="{{ inventory_hostname + ' ' + ansible_ssh_host }}"

    - name: install libselinux
      yum: name=libselinux-python state=present

    - name: install epel
      yum: name=epel-release state=present

    - name: add the upstream docker repository
      copy: src=files/docker-engine.repo dest=/etc/yum.repos.d/docker-engine.repo

    - name: install docker packages
      yum: 
        name: "{{ item }}"  
        state: latest
      with_items:
        - python-docker-py
        - docker-engine

    #- name: start docker
    #  service: name=docker state=running
    #- name: 
